spring:
  application:
    name: User_Service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: adil2197
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/app.log

server:
  port: 2000
